name: Issue Reminder
on:
  issues:
    types: [ opened ]

jobs:
  issue_comment:
    if: |
      (github.repository == 'AlexRogalskiy/object-mappers-playground')
    runs-on: ubuntu-latest
    steps:
      - name: Comment on issue
        uses: actions/github-script@0.9.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            var url = 'https://github.com/AlexRogalskiy/object-mappers-playground/blob/master/docs/user-guide/troubleshooting.md'
            var msg = `Thank you for opening an issue.  If this issue is related to a bug, please follow the steps and provide the information outlined in the [Troubleshooting Guide](${url}).  Failure to follow these instructions may result in automatic closing of this issue.`
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: msg
            })
